apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: abap-rag-minimal
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: extended
    spec: |
      predictor:
        containers:
        - name: kserve-container
          image: docker.io/acecross/abap-rag:0.2
          ports:
          - containerPort: 8080
