apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: abap-rag-server-v2                    # change if you want to reuse old name
  annotations:
    scenarios.ai.sap.com/name: abap-rag
    executables.ai.sap.com/name: rag-fastapi
  labels:
    ai.sap.com/version: "1.0.2"
    scenarios.ai.sap.com/id: "abap-rag"
spec:
  inputs:
    parameters:
      - name: image
        type: string
      - name: port
        type: string
        default: "8080"
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      name: "{{ name }}"
      annotations: |
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/target: 100
        autoscaling.knative.dev/targetBurstCapacity: 70
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets: 
          - name: ghcr                       # keep for private GHCR; remove if public
        minReplicas: 1
        maxReplicas: 2
        containers:
          - name: kserve-container           # required by validator
            image: "{{inputs.parameters.image}}"
            ports:
              - containerPort: {{inputs.parameters.port | int}}
                protocol: TCP
            env:
              - name: PORT
                value: "{{inputs.parameters.port | int}}"
              - name: LLM_PROVIDER
                value: "aicore"
              - name: LLM_MODEL
                value: "gpt-4o-mini"
            readinessProbe:
              httpGet:
                path: /healthz
                port: {{inputs.parameters.port | int}}
              initialDelaySeconds: 5
              periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /healthz
                port: {{inputs.parameters.port | int}}
              initialDelaySeconds: 15
              periodSeconds: 10
  resources:
    minReplicas: 1
    maxReplicas: 2
