apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: abap-rag-server-v2                    # change if you want to reuse old name
  annotations:
    scenarios.ai.sap.com/name: abap-rag
    executables.ai.sap.com/name: rag-fastapi
  labels:
    ai.sap.com/version: "1.0.2"
    scenarios.ai.sap.com/id: "abap-rag"
spec:
  inputs:
    parameters:
      - name: image
        type: string
      - name: port
        type: string
        default: "8080"
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: infer.s   # <-- set to a valid plan in your tenant
    spec: |
      predictor:
        # imagePullSecrets: []            # keep empty for public image
        containers:
        - name: kserve-container
          image: "nginxinc/nginx-unprivileged:stable-alpine"  # runs as non-root, default 8080
          ports:
          - containerPort: 8080
            protocol: TCP
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
          - name: PORT
            value: "8080"                 # env is string
          readinessProbe:
            httpGet:
              path: /
              port: 8080                  # numeric
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10


  resources:
    minReplicas: 1
    maxReplicas: 2
